GET http://localhost:3001/api/notes
### Request to get all notes
GET http://localhost:3001/api/notes/2
### Request to get note with id 2
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "This is a new note created via REST client",
  "important": true
}
### Request to create a new note
DELETE http://localhost:3001/api/notes/3